### ISSUE TITLE
xylodrone is coming to Bled techno bunker

### ISSUE THREAD

**Issue by yangwao** [yangwao/subhouse#1]
I've heard we've got first participant, Creative Pirate at [MetaPrime](https://metaprime.network) [@metaPrime](https://twitter.com/metaprime_net)

**Comment by vikiival** [comment]
```sql
postgres=# select  date '2022-07-29' - date '2021-11-25' as xylo_late;
 xylo_late
-----------
       246
(1 row)
```

**Comment by yangwao** [comment]
Been a nice summer '22 w @xylodrone
